/* ---------- navigation ---------- */
function showGame(name) {
  document.getElementById('menuView').classList.add('hidden');
    document.querySelectorAll('.game-view').forEach(v => v.classList.remove('active'));
      document.getElementById('view-' + name).classList.add('active');
        if (name === 'memory') setupMemory();
          if (name === 'morpion') setupMorpion();
            if (name === 'reflex') resetReflex();
              if (name === 'snake') drawSnakeIdle();
              }
              function backToMenu() {
                document.querySelectorAll('.game-view').forEach(v => v.classList.remove('active'));
                  document.getElementById('menuView').classList.remove('hidden');
                    if (snakeLoop) { clearInterval(snakeLoop); snakeLoop = null; }
                    }

                    /* ---------- SNAKE ---------- */
                    const snakeCanvas = document.getElementById('snakeCanvas');
                    const sctx = snakeCanvas.getContext('2d');
                    const CELL = 16, COLS = 20, ROWS = 20;
                    let snake, dir, nextDir, food, snakeScore, snakeLoop, snakeBest = 0;

                    function drawSnakeIdle() {
                      sctx.fillStyle = getComputedStyle(document.documentElement).getPropertyValue('--bg');
                        sctx.fillRect(0, 0, snakeCanvas.width, snakeCanvas.height);
                        }

                        function startSnake() {
                          snake = [{x:10,y:10},{x:9,y:10},{x:8,y:10}];
                            dir = {x:1,y:0}; nextDir = {x:1,y:0};
                              snakeScore = 0;
                                document.getElementById('snakeScore').textContent = 0;
                                  document.getElementById('snakeMsg').textContent = '';
                                    document.getElementById('snakeBtn').textContent = 'Relancer';
                                      placeFood();
                                        if (snakeLoop) clearInterval(snakeLoop);
                                          snakeLoop = setInterval(snakeTick, 110);
                                          }

                                          function placeFood() {
                                            food = { x: Math.floor(Math.random()*COLS), y: Math.floor(Math.random()*ROWS) };
                                              if (snake.some(s => s.x===food.x && s.y===food.y)) placeFood();
                                              }

                                              function snakeTick() {
                                                dir = nextDir;
                                                  const head = { x: snake[0].x + dir.x, y: snake[0].y + dir.y };
                                                    if (head.x < 0 || head.y < 0 || head.x >= COLS || head.y >= ROWS || snake.some(s => s.x===head.x && s.y===head.y)) {
                                                        clearInterval(snakeLoop); snakeLoop = null;
                                                            document.getElementById('snakeMsg').textContent = 'Perdu ! Score : ' + snakeScore;
                                                                if (snakeScore > snakeBest) { snakeBest = snakeScore; document.getElementById('snakeBest').textContent = snakeBest; }
                                                                    return;
                                                                      }
                                                                        snake.unshift(head);
                                                                          if (head.x === food.x && head.y === food.y) {
                                                                              snakeScore++;
                                                                                  document.getElementById('snakeScore').textContent = snakeScore;
                                                                                      placeFood();
                                                                                        } else {
                                                                                            snake.pop();
                                                                                              }
                                                                                                renderSnake();
                                                                                                }

                                                                                                function renderSnake() {
                                                                                                  const inkColor = getComputedStyle(document.documentElement).getPropertyValue('--ink');
                                                                                                    const coral = getComputedStyle(document.documentElement).getPropertyValue('--coral');
                                                                                                      sctx.fillStyle = getComputedStyle(document.documentElement).getPropertyValue('--bg');
                                                                                                        sctx.fillRect(0, 0, snakeCanvas.width, snakeCanvas.height);
                                                                                                          sctx.fillStyle = coral;
                                                                                                            sctx.fillRect(food.x*CELL, food.y*CELL, CELL-2, CELL-2);
                                                                                                              sctx.fillStyle = inkColor;
                                                                                                                snake.forEach(s => sctx.fillRect(s.x*CELL, s.y*CELL, CELL-2, CELL-2));
                                                                                                                }

                                                                                                                document.addEventListener('keydown', e => {
                                                                                                                  if (!snakeLoop) return;
                                                                                                                    const k = e.key;
                                                                                                                      if (k==='ArrowUp' && dir.y===0) nextDir = {x:0,y:-1};
                                                                                                                        else if (k==='ArrowDown' && dir.y===0) nextDir = {x:0,y:1};
                                                                                                                          else if (k==='ArrowLeft' && dir.x===0) nextDir = {x:-1,y:0};
                                                                                                                            else if (k==='ArrowRight' && dir.x===0) nextDir = {x:1,y:0};
                                                                                                                            });
                                                                                                                            let touchStart = null;
                                                                                                                            snakeCanvas.addEventListener('touchstart', e => { touchStart = e.touches[0]; }, {passive:true});
                                                                                                                            snakeCanvas.addEventListener('touchend', e => {
                                                                                                                              if (!touchStart || !snakeLoop) return;
                                                                                                                                const dx = e.changedTouches[0].clientX - touchStart.clientX;
                                                                                                                                  const dy = e.changedTouches[0].clientY - touchStart.clientY;
                                                                                                                                    if (Math.abs(dx) > Math.abs(dy)) {
                                                                                                                                        if (dx > 20 && dir.x===0) nextDir = {x:1,y:0};
                                                                                                                                            else if (dx < -20 && dir.x===0) nextDir = {x:-1,y:0};
                                                                                                                                              } else {
                                                                                                                                                  if (dy > 20 && dir.y===0) nextDir = {x:0,y:1};
                                                                                                                                                      else if (dy < -20 && dir.y===0) nextDir = {x:0,y:-1};
                                                                                                                                                        }
                                                                                                                                                        }, {passive:true});

                                                                                                                                                        /* ---------- REFLEX ---------- */
                                                                                                                                                        let reflexState = 'idle', reflexTimer = null, reflexStart = 0, reflexBest = null;
                                                                                                                                                        const reflexBox = document.getElementById('reflexBox');

                                                                                                                                                        function resetReflex() {
                                                                                                                                                          reflexState = 'idle';
                                                                                                                                                            reflexBox.className = 'reflex-box reflex-wait';
                                                                                                                                                              reflexBox.textContent = 'Clique pour commencer';
                                                                                                                                                              }

                                                                                                                                                              function reflexClick() {
                                                                                                                                                                if (reflexState === 'idle') {
                                                                                                                                                                    reflexState = 'waiting';
                                                                                                                                                                        reflexBox.className = 'reflex-box reflex-wait';
                                                                                                                                                                            reflexBox.textContent = 'Attends le vert...';
                                                                                                                                                                                const delay = 1000 + Math.random()*2500;
                                                                                                                                                                                    reflexTimer = setTimeout(() => {
                                                                                                                                                                                          reflexState = 'go';
                                                                                                                                                                                                reflexStart = performance.now();
                                                                                                                                                                                                      reflexBox.className = 'reflex-box reflex-go';
                                                                                                                                                                                                            reflexBox.textContent = 'Clique !';
                                                                                                                                                                                                                }, delay);
                                                                                                                                                                                                                  } else if (reflexState === 'waiting') {
                                                                                                                                                                                                                      clearTimeout(reflexTimer);
                                                                                                                                                                                                                          reflexState = 'idle';
                                                                                                                                                                                                                              reflexBox.className = 'reflex-box reflex-early';
                                                                                                                                                                                                                                  reflexBox.textContent = 'Trop tôt ! Reclique pour réessayer';
                                                                                                                                                                                                                                    } else if (reflexState === 'go') {
                                                                                                                                                                                                                                        const t = Math.round(performance.now() - reflexStart);
                                                                                                                                                                                                                                            document.getElementById('reflexLast').textContent = t + ' ms';
                                                                                                                                                                                                                                                if (reflexBest === null || t < reflexBest) {
                                                                                                                                                                                                                                                      reflexBest = t;
                                                                                                                                                                                                                                                            document.getElementById('reflexBest').textContent = t + ' ms';
                                                                                                                                                                                                                                                                }
                                                                                                                                                                                                                                                                    reflexState = 'idle';
                                                                                                                                                                                                                                                                        reflexBox.className = 'reflex-box reflex-wait';
                                                                                                                                                                                                                                                                            reflexBox.textContent = 'Clique pour rejouer';
                                                                                                                                                                                                                                                                              }
                                                                                                                                                                                                                                                                              }

                                                                                                                                                                                                                                                                              /* ---------- MEMORY ---------- */
                                                                                                                                                                                                                                                                              const emojis = ['🍎','🍌','🍇','🍉','🍒','🍋','🍓','🥝'];
                                                                                                                                                                                                                                                                              let memFirst = null, memLock = false, memMoves = 0, memPairs = 0;

                                                                                                                                                                                                                                                                              function setupMemory() {
                                                                                                                                                                                                                                                                                const deck = [...emojis, ...emojis].sort(() => Math.random()-0.5);
                                                                                                                                                                                                                                                                                  memFirst = null; memLock = false; memMoves = 0; memPairs = 0;
                                                                                                                                                                                                                                                                                    document.getElementById('memMoves').textContent = 0;
                                                                                                                                                                                                                                                                                      document.getElementById('memPairs').textContent = 0;
                                                                                                                                                                                                                                                                                        const grid = document.getElementById('memoryGrid');
                                                                                                                                                                                                                                                                                          grid.innerHTML = '';
                                                                                                                                                                                                                                                                                            deck.forEach((emo, i) => {
                                                                                                                                                                                                                                                                                                const card = document.createElement('div');
                                                                                                                                                                                                                                                                                                    card.className = 'memory-card';
                                                                                                                                                                                                                                                                                                        card.dataset.emo = emo;
                                                                                                                                                                                                                                                                                                            card.dataset.idx = i;
                                                                                                                                                                                                                                                                                                                card.textContent = '';
                                                                                                                                                                                                                                                                                                                    card.addEventListener('click', () => flipMemCard(card));
                                                                                                                                                                                                                                                                                                                        grid.appendChild(card);
                                                                                                                                                                                                                                                                                                                          });
                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                          function flipMemCard(card) {
                                                                                                                                                                                                                                                                                                                            if (memLock || card.classList.contains('flipped') || card.classList.contains('matched')) return;
                                                                                                                                                                                                                                                                                                                              card.classList.add('flipped');
                                                                                                                                                                                                                                                                                                                                card.textContent = card.dataset.emo;
                                                                                                                                                                                                                                                                                                                                  if (!memFirst) { memFirst = card; return; }
                                                                                                                                                                                                                                                                                                                                    memMoves++;
                                                                                                                                                                                                                                                                                                                                      document.getElementById('memMoves').textContent = memMoves;
                                                                                                                                                                                                                                                                                                                                        memLock = true;
                                                                                                                                                                                                                                                                                                                                          if (memFirst.dataset.emo === card.dataset.emo) {
                                                                                                                                                                                                                                                                                                                                              memFirst.classList.add('matched');
                                                                                                                                                                                                                                                                                                                                                  card.classList.add('matched');
                                                                                                                                                                                                                                                                                                                                                      memPairs++;
                                                                                                                                                                                                                                                                                                                                                          document.getElementById('memPairs').textContent = memPairs;
                                                                                                                                                                                                                                                                                                                                                              memFirst = null; memLock = false;
                                                                                                                                                                                                                                                                                                                                                                } else {
                                                                                                                                                                                                                                                                                                                                                                    setTimeout(() => {
                                                                                                                                                                                                                                                                                                                                                                          memFirst.classList.remove('flipped'); memFirst.textContent = '';
                                                                                                                                                                                                                                                                                                                                                                                card.classList.remove('flipped'); card.textContent = '';
                                                                                                                                                                                                                                                                                                                                                                                      memFirst = null; memLock = false;
                                                                                                                                                                                                                                                                                                                                                                                          }, 700);
                                                                                                                                                                                                                                                                                                                                                                                            }
                                                                                                                                                                                                                                                                                                                                                                                            }

                                                                                                                                                                                                                                                                                                                                                                                            /* ---------- MORPION ---------- */
                                                                                                                                                                                                                                                                                                                                                                                            let morBoard, morTurn, morOver;
                                                                                                                                                                                                                                                                                                                                                                                            function setupMorpion() {
                                                                                                                                                                                                                                                                                                                                                                                              morBoard = Array(9).fill(null);
                                                                                                                                                                                                                                                                                                                                                                                                morTurn = 'X'; morOver = false;
                                                                                                                                                                                                                                                                                                                                                                                                  document.getElementById('morpionMsg').textContent = 'Au tour de X';
                                                                                                                                                                                                                                                                                                                                                                                                    const grid = document.getElementById('morpionGrid');
                                                                                                                                                                                                                                                                                                                                                                                                      grid.innerHTML = '';
                                                                                                                                                                                                                                                                                                                                                                                                        for (let i=0;i<9;i++) {
                                                                                                                                                                                                                                                                                                                                                                                                            const cell = document.createElement('button');
                                                                                                                                                                                                                                                                                                                                                                                                                cell.className = 'morpion-cell';
                                                                                                                                                                                                                                                                                                                                                                                                                    cell.addEventListener('click', () => morClick(i, cell));
                                                                                                                                                                                                                                                                                                                                                                                                                        grid.appendChild(cell);
                                                                                                                                                                                                                                                                                                                                                                                                                          }
                                                                                                                                                                                                                                                                                                                                                                                                                          }

                                                                                                                                                                                                                                                                                                                                                                                                                          function morClick(i, cell) {
                                                                                                                                                                                                                                                                                                                                                                                                                            if (morOver || morBoard[i]) return;
                                                                                                                                                                                                                                                                                                                                                                                                                              morBoard[i] = morTurn;
                                                                                                                                                                                                                                                                                                                                                                                                                                cell.textContent = morTurn;
                                                                                                                                                                                                                                                                                                                                                                                                                                  cell.disabled = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                    const win = morCheckWin();
                                                                                                                                                                                                                                                                                                                                                                                                                                      if (win) {
                                                                                                                                                                                                                                                                                                                                                                                                                                          morOver = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                              document.getElementById('morpionMsg').textContent = win + ' gagne !';
                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                      if (morBoard.every(c => c)) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                          morOver = true;
                                                                                                                                                                                                                                                                                                                                                                                                                                                              document.getElementById('morpionMsg').textContent = 'Match nul';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                  return;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                      morTurn = morTurn === 'X' ? 'O' : 'X';
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        document.getElementById('morpionMsg').textContent = 'Au tour de ' + morTurn;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                        }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                        function morCheckWin() {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                          const lines = [[0,1,2],[3,4,5],[6,7,8],[0,3,6],[1,4,7],[2,5,8],[0,4,8],[2,4,6]];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                            for (const [a,b,c] of lines) {
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                if (morBoard[a] && morBoard[a]===morBoard[b] && morBoard[a]===morBoard[c]) return morBoard[a];
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                  }
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    return null;
                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    }

                                                                                                                                                                                                                                                                                                                                                                                                                                                                                    drawSnakeIdle();